name: Build and test Micron Language Interpreter from latest commit on master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test Micron Language Interpreter from latest commit on master branch
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
      
    - name: Print Go version
      run: go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -a .

    - name: Test
      run: go test -v ./...
